version: '3'

networks:
  service_network:
    driver: bridge

services:
  user:
    build: ./microservices/user
    environment:
      USER_DB_NAME: ${USER_DB_NAME}
      USER_HOST_PORT: ${USER_HOST_PORT}
    ports:
      - "${USER_HOST_PORT}:${USER_HOST_PORT}"
    depends_on:
      - user-db
    networks:
      - service_network

  user-db:
    image: mysql:8.0.26
    command: --sql-mode=NO_ENGINE_SUBSTITUTION,STRICT_TRANS_TABLES
    ports:
      - "${USER_DB_HOST_PORT}:3306"
    volumes:
      - ./microservices/user/db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - service_network

  disaster:
    build: ./microservices/disaster
    environment:
      DISASTER_DB_NAME: ${DISASTER_DB_NAME}
      DISASTER_HOST_PORT: ${DISASTER_HOST_PORT}
    ports:
      - "${DISASTER_HOST_PORT}:${DISASTER_HOST_PORT}"
    depends_on:
      - disaster-db
    networks:
      - service_network

  disaster-db:
    image: mysql:8.0.26
    ports:
      - "${DISASTER_DB_HOST_PORT}:3306"
    volumes:
      - ./microservices/disaster/db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_INIT_COMMAND: "SET GLOBAL sql_mode=''"
    networks:
      - service_network

  volunteerevent:
    build: ./microservices/volunteerevent
    environment:
      VOLUNTEEREVENT_DB_NAME: ${VOLUNTEEREVENT_DB_NAME}
      VOLUNTEEREVENT_HOST_PORT: ${VOLUNTEEREVENT_HOST_PORT}
    ports:
      - "${VOLUNTEEREVENT_HOST_PORT}:${VOLUNTEEREVENT_HOST_PORT}"
    depends_on:
      - volunteerevent-db
    networks:
      - service_network

  volunteerevent-db:
    image: mysql:8.0.26
    ports:
      - "${VOLUNTEEREVENT_DB_HOST_PORT}:3306"
    volumes:
      - ./microservices/volunteerevent/db.sql:/docker-entrypoint-initdb.d/db.sql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    networks:
      - service_network

  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      MYSQL_INIT_COMMAND: "SET GLOBAL sql_mode=''"
    ports:
      - "${RABBITMQ_PORT}:${RABBITMQ_PORT}"
      - "15672:15672"
    networks:
      - service_network

  rabbitmq-setup:
    build: ./microservices/amqp
    environment:
      RABBITMQ_PORT: ${RABBITMQ_PORT}
    depends_on:
      - rabbitmq
    networks:
      - service_network

  getalert:
    build: ./microservices/getalert
    environment:
      RABBITMQ_PORT: ${RABBITMQ_PORT}
    depends_on:
      - rabbitmq
    networks:
      - service_network
      

  websocket:
    build: ./microservices/app_websocket
    environment:
      SAFEME_WEBSOCKET_HOST_PORT: ${SAFEME_WEBSOCKET_HOST_PORT}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
    ports:
      - "${SAFEME_WEBSOCKET_HOST_PORT}:${SAFEME_WEBSOCKET_HOST_PORT}"
    depends_on:
      - rabbitmq
    networks:
      - service_network
      
    
  createdisaster:
    build: ./microservices/createdisaster
    environment:
      USER_HOST_PORT: ${USER_HOST_PORT}
      DISASTER_HOST_PORT: ${DISASTER_HOST_PORT}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
    depends_on:
      - rabbitmq
    networks:
      - service_network
    restart: "always"
      
  