version: "3.8"

services:
# Initiate and start all microservices image in Docker from microservices folder
user:
  build:
    context: ./microservices
    dockerfile: user.Dockerfile
  image: chrysaorsly/user:esd
  restart: always
  environment:
    dbURL: mysql+mysqlconnector://is213@host.docker.internal:3306/user
