version: '3'
services:
  db:
    image: mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      - HOST_PORT=${HOST_PORT}
    volumes:
      - ./sql-files:/docker-entrypoint-initdb.d
    ports:
      - "${HOST_PORT}:3306"